In [1]:
# #다차원배열 행렬

# 차원주는 ndim 으로 확인
# 형상은  shape으로 확인

# 처음 차원은 0 다음은 1
# 2차원 배열은 matrix 라고 부름


import numpy as np

A = np.array([1,2,3,4])
print(A)
print(np.ndim(A))
print(A.shape)

[1 2 3 4]
1
(4,)


In [3]:
B = np.array([[1,2],[3,4],[5,6]])
print(B)
print(np.ndim(B))
print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [4]:
#행렬의 연산 덧셈 상수배 곱셈

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [6]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])

print(A.shape)
print(B.shape)

print(A)
print(B)

np.dot(A,B)

(2, 3)
(3, 2)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


array([[22, 28],
       [49, 64]])

In [8]:
#신경망에서 작동방식이 행렬의 곱, 계산과 일치
# 입력값 x  가중치 w 출력값 y로 나오게 됨

X = np.array([[1,2]])
W = np.array([[1,3,5],[2,4,6]])

print(X.shape)
print(W.shape)

print(X)
print(W)

np.dot(X,W)




(1, 2)
(2, 3)
[[1 2]]
[[1 3 5]
 [2 4 6]]


array([[ 5, 11, 17]])

![alt text](image-3.png)